version: '2'
services:
  web:
    build: .
    image: hesrecipes_web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_LOG_TO_STDOUT=1
    volumes:
      - .:/hesrecipes
    ports:
      - "3000:3000"
